spring.application.name=demo
server.port=8081

# Configuración del contexto de la aplicación para que todas las rutas comiencen con /api
server.servlet.context-path=/api

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:mydb

# Configuración del driver de la base de datos H2
spring.datasource.driver.class-name=org.h2.Driver

# Credenciales de la base de datos H2
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA para crear y eliminar las tablas automáticamente al iniciar y cerrar la aplicación
spring.jpa.hibernate.ddl-auto=create-drop

# Habilitar la consola web de H2 para facilitar la visualización y manipulación de la base de datos en memoria
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración para que la inicialización de la base de datos se realice después de que JPA haya creado las tablas 
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always